openapi: "3.0.0"
info:
  title: example-app-backend
  description: This is a sample backend service for a demo app.
  contact:
    name: Lukas Stawik
    email: lukas.stawik@gmail.com
  version: 1.0.0
paths:
  /api/version:
    get:
      summary: Show API version
      responses:
        "200":
          description: |-
            200 response
          content:
            application/json:
              examples:
                foo:
                  value: { "version": "v1.0.0" }
